Moving the coordination number to mctc-lib
grimme-lab/mctc-lib pull request #71
Opened 2024-11-10 21:28 UTC by thfroitzheim

It would be quite beneficial to have a centralized place to calculate the CN since it appears in all of our projects (xtb, tblite, dftd4, dftd3, multicharge, DRACO, ...). Moreover, there are now several different CNs based on slight variations of the counting function, which must be integrated in several places. 

`mctc-lib` might be the right spot since it is purely based on the structure, but I am open to alternatives (@awvwgk, @Albkat, @marvinfriede). As an example, I moved the tblite implementation to the mctc-lib. This also includes the cutoffs for periodicity and part of the data sections (maybe we should move the whole as literature radii and EN are also frequently used). 

If we should do this, I will still clean up a few things in the CN (i.e. rename the gfn CN to dexp for double exponential) to make it general.

2024-11-10 21:41 UTC, awvwgk requested changes
The update for the GH actions can be a separate PR.

2024-11-10 21:55 UTC, thfroitzheim commented
Sure. I moved the update of the GH actions to (#72). 

I am mostly interested if you think that mctc-lib is the right place for the coordination numbers.

2024-11-11 00:02 UTC, marvinfriede commented
I agree with moving the CNs and data here. I also did that for the autodiff versions ([CN](https://github.com/tad-mctc/tad-mctc/tree/main/src/tad_mctc/ncoord), [data](https://github.com/tad-mctc/tad-mctc/tree/main/src/tad_mctc/data)).

2025-03-17 23:02 UTC, thfroitzheim commented
I think this is now ready. I opened draft PRs for the changes necessary in dftd4, simple-dftd3, multicharge, and tblite. Currently, they point to this branch and will be updated to the mctc-lib head as soon as this PR is merged. 

This PR collects all coordination numbers with different counting functions, electronegativity dependences, and cutoffs in mctc-lib. They are used via a coordination number type. Additionally, common data such as Pauling electronegativity or different radii are collected in mctc-lib.

2025-03-18 13:08 UTC, marvinfriede commented on src/mctc/ncoord.f90
> +   case("exp")
Can we use an enum here? See [here](https://github.com/dftd4/dftd4/blob/00d331bf657ebca20f161eeabd2979dd835dd1d3/src/dftd4/model/type.f90#L154) and [here](https://github.com/dftd4/dftd4/blob/00d331bf657ebca20f161eeabd2979dd835dd1d3/src/dftd4/model/d4s.f90#L320) for an example.

2025-03-18 13:09 UTC, marvinfriede commented on src/mctc/ncoord/dexp.f90
> +
```suggestion
Real-space cutoff for coordination number
```

2025-03-18 13:11 UTC, marvinfriede commented on src/mctc/ncoord/dexp.f90
> +
```suggestion
   Real-space cutoff for coordination number
```

2025-03-18 13:13 UTC, marvinfriede commented on src/mctc/ncoord/dexp.f90
> +   count = (-k*r0*expterm)/(r**2*((expterm+1._wp)**2))
```suggestion
   count = (-k*r0*expterm)/(r**2.0_wp*((expterm+1.0_wp)**2.0_wp))
```

2025-03-18 13:13 UTC, marvinfriede commented on src/mctc/ncoord/dexp.f90
> +   expterm = exp(-k*(r0/r-1._wp))
```suggestion
   expterm = exp(-k*(r0/r-1.0_wp))
```

2025-03-18 13:15 UTC, marvinfriede commented on src/mctc/ncoord/erf.f90
> +      expterm = exp(-exponent**2)
```suggestion
      expterm = exp(-exponent**2.0_wp)
```

2025-03-18 13:15 UTC, marvinfriede commented on src/mctc/ncoord/erf/dftd4.f90
> +
```suggestion

   !> Real-space cutoff
```

2025-03-18 13:16 UTC, marvinfriede commented on src/mctc/ncoord/erf/dftd4.f90
> +      en_factor = k4*exp(-(abs(self%en(izp)-self%en(jzp)) + k5)**2/k6)
```suggestion
      en_factor = k4*exp(-(abs(self%en(izp)-self%en(jzp)) + k5)**2.0_wp/k6)
```

2025-03-18 13:17 UTC, marvinfriede commented on src/mctc/ncoord/erf/en.f90
> +   !> Evaluates pairwise electronegativity factor if non applies
What does "if non applies" mean?

2025-03-18 13:18 UTC, marvinfriede commented on src/mctc/ncoord/exp.f90
> +   real(wp), parameter :: default_cutoff = 25.0_wp
```suggestion
   !> Real-space cutoff
   real(wp), parameter :: default_cutoff = 25.0_wp
```

2025-03-18 13:18 UTC, marvinfriede commented on src/mctc/ncoord/exp.f90
> +      count = (-self%kcn*rc*expterm)/(r**2*((expterm+1._wp)**2))
```suggestion
      expterm = exp(-self%kcn*(rc/r-1.0_wp))
      count = (-self%kcn*rc*expterm)/(r**2.0_wp*((expterm+1.0_wp)**2.0_wp))
```

2025-03-18 13:19 UTC, marvinfriede commented on src/mctc/ncoord/type.f90
> +         import :: ncoord_type, wp
Why the import here?

2025-03-18 13:22 UTC, marvinfriede commented on test/testsuite_structure.f90
> +   character(len=*), parameter :: sym(nat) = [character(len=4)::&
What changed here and why?

2025-03-18 15:35 UTC, thfroitzheim commented on test/testsuite_structure.f90
> +   character(len=*), parameter :: sym(nat) = [character(len=4)::&
This is just the consistent structure with mstore. With the old structure it works too but since it is a defined structure with a name, I want it to be consistent.

2025-03-19 07:26 UTC, marvinfriede commented on src/mctc/ncoord/type.f90
> +      !$omp reduction(+:gradient, sigma) &
Maybe we should remove the reduction to avoid `ulimit -s unlimited`.

2025-03-19 07:27 UTC, marvinfriede commented on src/mctc/ncoord.f90
> +   !> Optional set of electronegativity to be use din CN
```suggestion
   !> Optional set of electronegativity to be used in CN
```

2025-03-19 07:46 UTC, Albkat commented on src/mctc/ncoord/type.f90
> +      !$omp reduction(+:gradient, sigma) &
Any ideas how to achieve this?

2025-03-19 07:59 UTC, marvinfriede commented on src/mctc/ncoord/type.f90
> +      !$omp reduction(+:gradient, sigma) &
https://github.com/dftd4/dftd4/pull/262#discussion_r1830556898

2025-03-19 08:29 UTC, marvinfriede commented on src/mctc/ncoord/type.f90
> +      !$omp reduction(+:gradient, sigma) &
Let's do this in a separate PR, as discussed with @thfroitzheim.

2025-03-19 08:33 UTC, merged